repos:
-   repo: https://github.com/ambv/black
    rev: "23.10.1"
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
    - id: mixed-line-ending
    - id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.0"
    hooks:
    - id: mypy
      additional_dependencies: [
        "numpy>=1.20",
        "asyncssh>=2.9",
        "prompt_toolkit>=3.0.29",
        "types-setuptools",
        "pytest",
      ]
      args: []
