[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython>=0.29.13",
    "oldest-supported-numpy",
]
build-backend = "setuptools.build_meta"

[tool.mypy]
warn_return_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true